### ISSUE TITLE
Ip address leak

### ISSUE THREAD

**Issue by charleschege** [geph-official/geph4-client#22]
The public ip address leaks on Linux even though the IP address is detected as United States(or any other geph server). This seems to be dangerous as someone knows exactly the country, ISP and IP address you are connecting from.

Even when geph is run as root.

**Comment by charleschege** [comment]
This does not seem to be the case on android using the official geph apk from play store. I am using Firefox with maximum privacy settings on both Linux and android devices using the site https://whatleaks.com/

On  Linux the public ip address leaks on Javascript webrtc

**Comment by charleschege** [comment]
testing with another vpn such as proton vpn does not leak the private address and somehow disables webrtc transport. could geph be able to prevent such protocols that leak public ip addresses? like webrtc

**Comment by nullchinchilla** [comment]
> testing with another vpn such as proton vpn does not leak the private address and somehow disables webrtc transport. could geph be able to prevent such protocols that leak public ip addresses? like webrtc

That wouldn't really be possible without doing weird things like reconfiguring your browser behind your back. Unfortunately I don't think things like WebRTC leaks can be fixed by a proxy software, at least when running in "proxy mode" (non-VPN mode).

What exactly is being leaked? Are you using VPN mode or not? Can you show me a screenshot of something like whatleaks.com ?

**Comment by charleschege** [comment]
This issue no longer occurs
