### ISSUE TITLE
Feature request: add support for IPv6 only network environment

### ISSUE THREAD

**Issue by showgood163** [geph-official/geph4-client#6]
[Old issue here](https://github.com/geph-official/geph2/issues/60)

For now, I didn't see this options on both android and windows client.

**Comment by nullchinchilla** [comment]
Right now, that is fairly difficult, because it requires that the entire infrastructure, including bridges used for censorship circumvention, support IPv6. Unfortunately, we often use "weird" connections, like home internet connections in Taiwan, for bridges in order to provide fast access to Mainland China at a reasonable cost. These connections often do not have IPv6 support.

I don't believe that truly IPv6-only networks, which are unable to access IPv4-only hosts, are something you encounter in the wild though. Do you mean IPv6-first networks using 464XLAT, like T-Mobile? I belive Geph already works pretty well on these networks (I actually use T-Mobile myself)

**Comment by showgood163** [comment]
From my perspective, "ipv6 only support" only restricts the connections between the client (end user) and the server (you, the service provider). I don't know how packages are routed among your infrastructures since it's transparent to me, so I won't put restrictions on these connections.

I'm actually in ipv6 only environment right now (like cernet). I refuse to use ipv4 because in mainland China, the censorship on ipv4 is much more aggressive than that on ipv6.

**Comment by nullchinchilla** [comment]
Well, censorship through Geph is non-existent :)

Why not just turn on IPv4 and also Geph? IPv6 routing in China also really, really sucks and it's very hard to write something that'll perform well on China's IPv6 network. Also, all the GFW features will almost certainly be ported to IPv6 sooner or later.

**Comment by showgood163** [comment]
Well, you have your points, but that's not feasible for my network environment.

Let me reiterate my points.
- Ipv6 connections provide more safety assurances for end users (which aligns with your initiative).
- For ipv6 only mode, I can accept fewer available servers. (Background: I have purchased your service and have end devices in dual stack environment, I also have machines in ipv6 only environment.)
- I can lend some help on testing if you actually want to make this happen.
