### ISSUE TITLE
Latest version did not work on MacOS 10.14.6

### ISSUE THREAD

**Issue by HertCZ** [geph-official/geph4-client#84]
The latest version does not work on MacOS 10.14.6. It keeps crashing. Please solve this problem or make an old version available for download. Thanks.

**Comment by nullchinchilla** [comment]
Can you give more info about what crashes? Is it the GUI or this executable (`geph4-client`)?

**Comment by HertCZ** [comment]
Hi Eric, Thanks for your email. It is the 4.6 and 4.7 version of the GUI. As there are no alerts or logs after the crash, I cannot give you a crash log or anything that records the running of the application. My observation is that when I try to run it after installation, nothing happens. No animation, no crash alert, no GUI. Hope the above would be helpful~27.01.2023, 22:36, "Eric Tung" ***@***.***>:
Can you give more info about what crashes? Is it the GUI or this executable (geph4-client)?

**Comment by hokhyk** [comment]
> Can you give more info about what crashes? Is it the GUI or this executable (`geph4-client`)?
Process:               gephgui-wry [7606]
Path:                  /Applications/Geph.app/Contents/MacOS/./bin/gephgui-wry
Identifier:            io.geph.GephGui
Version:               4.5 (4.5)
Code Type:             X86-64 (Native)
Parent Process:        ??? [7604]
Responsible:           gephgui-wry [7606]
User ID:               501

Date/Time:             2023-04-01 19:15:35.272 +1300
OS Version:            Mac OS X 10.14.6 (18G9323)
Report Version:        12
Anonymous UUID:        08A05B71-86FE-8CBC-4CF0-E2B4242E39F9

Sleep/Wake UUID:       DF00D71B-D91D-4DDD-B0FD-BE275E0DEC56

Time Awake Since Boot: 640000 seconds
Time Since Wake:       2400 seconds

System Integrity Protection: enabled

Crashed Thread:        11  isahc-agent-0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/Geph.app/Contents/MacOS/./bin/gephgui-wry (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
